approve_label: "approved"
problem_label: "needs some work"
ignore_label: "skip validation"

forbidden_targets: ["master"]
forbidden_sources:
  ["master", "maintenance", "devel", "staging/maintenance", "staging/devel"]

labels:
  docs:
    forbidden_targets: []
  meta:
    forbidden_targets: []
  ci/cd:
    forbidden_targets: []
