exclude: ^(src/octoprint/vendor/|src/octoprint/static/js/lib|src/octoprint/static/vendor|tests/static/js/lib|tests/util/_files|docs/|scripts/|translations/|versioneer.py|.*\.css|.*\.svg)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: https://github.com/OctoPrint/codemods
    rev: 0.4.0
    hooks:
      - id: codemod_detect_past_builtins_imports
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_dict_comprehension_to_literal
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_dict_to_literal
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_not_in
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_oserror_merge
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_py3_class_inheritance
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_py3_super
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_remove_builtins_imports
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_remove_float_conversion
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_remove_future_imports
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_set_to_literal
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_string_encoding
        args: ["--ignore", "src/octoprint/vendor"]
      - id: codemod_yield_from_generator
        args: ["--ignore", "src/octoprint/vendor"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["--config", "black.toml"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.19.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.19.0
          - eslint-plugin-es5@v1.3.0
          - eslint-plugin-cypress@2.11.2
        files: \.js$
        exclude: ^(src/octoprint/vendor/|tests/static/js/lib|tests/util/_files|docs/|scripts/|translations/)
